feat: add variable rds_deletion_protection
escaletech/terraform-modules pull request #144
Opened 2023-01-17 19:41 UTC by SimoneShibata

2023-01-17 19:45 UTC, lguerrero-1807 requested changes
Acho que pode valer a pena deixar sempre habilitado o delete protection. Nesse caso trocaria para true o default.

2023-01-17 19:49 UTC, SimoneShibata commented
o padrão é false https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#deletion_protection

mas posso deixar como true

2023-01-17 23:52 UTC, bruno-vicoso approved these changes
LGTM

2023-01-18 13:32 UTC, lguerrero-1807 approved these changes

2023-01-18 13:38 UTC, merged